services:
  - type: web
    name: gaming-hub
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PORT
        value: 10000

  - type: cron
    name: atualizar-precos
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ATUALIZAR_PRECOS.py"
    schedule: "0 */2 * * *"
